[project]
name = "tetris-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[other]>=1.1.1",
    "imageio>=2.37.0",
    "matplotlib>=3.10.1",
    "tetris-gymnasium>=0.3.0",
    "torch>=2.6.0",
]
